<?php include 'Layout/header.phtml';?>
        <section class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            Painel
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4 text-center">
                                    <a href="/users">
                                        <button type="button" class="btn btn-secondary"><i class="fa fa-user fa-3x"></i></button>
                                        <br>
                                        <span>Usuários</span>
                                    </a>
                                </div>
                                <div class="col-md-4 text-center">
                                    <a href="/employees">
                                        <button type="button" class="btn btn-secondary"><i class="fa fa-users fa-3x"></i></button>
                                        <br>
                                        <span>Colaboradores</span>
                                    </a>
                                </div>
                                <div class="col-md-4 text-center">
                                    <a href="/all-overtimes">
                                        <button type="button" class="btn btn-secondary"><i class="fa fa-clock fa-3x"></i></button>
                                        <br>
                                        <span>Banco de Horas</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
<?php include 'Layout/footer.phtml';?>