<?php include 'Layout/header.phtml';?>
        <section class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            Painel
                        </div>
                        <div class="card-body">

                        </div>
                    </div>
                </div>
            </div>
        </section>
<?php include 'Layout/footer.phtml';?>