<?php
$id = "";
$name = "";
$email = "";
$telephone = "";
$hired_at = "";
if (isset($employee['id'])) {
    $id = $employee['id'];
}
if (isset($employee['name'])) {
    $name = $employee['name'];
}
if (isset($employee['email'])) {
    $email = $employee['email'];
}
if (isset($employee['telephone'])) {
    $telephone = $employee['telephone'];
}
if (isset($employee['hired_at'])) {
    $hired_at = $employee['hired_at'];
}
include "Layout/header.phtml";
?>
    <section class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Cadastrar/Editar Colaborador
                        <a href="/employees"><button class="btn-sm btn-primary custom-right"><i class="fa fa-arrow-left"></i></button></a>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div style="margin: 0 auto 0 auto; height: auto; width: 50%;">
                                <form method="post" action="/employees/save">
                                    <input type="hidden" name="id" value="<?php echo $id; ?>">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="basic-addon1">Nome</span>
                                        </div>
                                        <input type="text" name="name" class="form-control" autocomplete="off" placeholder="Informe o nome do Usuário." value="<?php echo $name; ?>" aria-label="Nome" aria-describedby="basic-addon1">
                                    </div>
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="basic-addon1">E-mail</span>
                                        </div>
                                        <input type="email" name="email" class="form-control" autocomplete="off" placeholder="Informe um e-mail válido." value="<?php echo $email; ?>" aria-label="E-mail" aria-describedby="basic-addon1" required>
                                    </div>
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="basic-addon1">Telefone</span>
                                        </div>
                                        <input type="text" name="telephone" class="form-control" autocomplete="off" placeholder="Telefone de contato do colaborador." value="<?php echo $telephone; ?>" aria-label="Telefone" aria-describedby="basic-addon1">
                                    </div>
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="basic-addon1">Data de Contratação</span>
                                        </div>
                                        <input type="date" name="hired_at" class="form-control" autocomplete="off" aria-label="Data de Contratação" aria-describedby="basic-addon1" value="<?php echo $hired_at; ?>">
                                    </div>
                                    <div class="text-center">
                                        <button type="submit" class="btn btn-success btn-sm">Salvar</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php include 'Layout/footer.phtml';?>