<?php include 'Layout/header.phtml'; ?>
    <section class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Colaboradores
                        <a href="/employees/register"><button class="btn-sm btn-primary custom-right"><i class="fa fa-plus"></i></button></a>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-dark table-hover" id="table">
                            <thead>
                            <tr>
                                <th scope="col" width="1%">#</th>
                                <th scope="col">Nome</th>
                                <th scope="col">Email</th>
                                <th scope="col">Telefone</th>
                                <th scope="col">Data de Contratação</th>
                                <th scope="col" width="5%">Horas</th>
                                <th scope="col" width="5%">Editar</th>
                                <th scope="col" width="5%">Excluir</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            $count = 1;
                            foreach ($employees['data'] as $value) {
                                $ct = ($count < 10) ? '0' . $count : $count;
                                $hire = explode("-", $value['hired_at']);
                                $hired_at = $hire[2] . "/" . $hire[1] . "/" . $hire[0]
                            ?>
                            <tr>
                                <td class="text-center" scope="row"><?=$ct;?></td>
                                <td><?=$value['name'];?></td>
                                <td><?=$value['email'];?></td>
                                <td><?=$value['telephone'];?></td>
                                <td class="text-center"><?=$hired_at;?></td>
                                <td class="text-center">
                                    <form method="post" action="/overtimes">
                                        <input type="hidden" name="employee_id" value="<?=$value['id'];?>">
                                        <button type="submit" class="btn-sm btn-primary"><i class="fa fa-clock"></i></button>
                                    </form>
                                </td>
                                <td class="text-center">
                                    <form method="post" action="/employees/register">
                                        <input type="hidden" name="id" value="<?=$value['id'];?>">
                                        <button type="submit" class="btn-sm btn-warning"><i class="fa fa-edit"></i></button>
                                    </form>
                                </td>
                                <td class="text-center">
                                    <form method="post" action="/employees/delete">
                                        <input type="hidden" name="id" value="<?=$value['id'];?>">
                                        <button type="submit" class="btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                            <?php
                                $count++;
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php include 'Layout/footer.phtml';?>