<?php include 'Layout/header.phtml'; ?>
    <section class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Usuários
                        <a href="/users/create"><button class="btn-sm btn-primary custom-right"><i class="fa fa-plus"></i></button></a>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-dark">
                            <thead>
                            <tr>
                                <th scope="col" width="1%">#</th>
                                <th scope="col">Nome</th>
                                <th scope="col">Email</th>
                                <th scope="col" width="5%">Editar</th>
                                <th scope="col" width="5%">Excluir</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            $count = 1;
                            foreach ($users['data'] as $value) {
                                $ct = ($count < 10) ? '0' . $count : $count;
                            ?>
                            <tr>
                                <td class="text-center" scope="row"><?=$ct;?></td>
                                <td><?php echo $value['name'];?></td>
                                <td><?php echo$value['email'];?></td>
                                <td class="text-center"><button class="btn-sm btn-warning"><i class="fa fa-edit"></i></button></td>
                                <td class="text-center"><button class="btn-sm btn-danger"><i class="fa fa-trash"></i></button></td>
                            </tr>
                            <?php
                                $count++;
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php include 'Layout/footer.phtml';?>