</div>
<footer class="bg-secondary custom-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <p class="mb-0">&copy; Todos os direitos reservados para <a class="text-300" href="https://wagner.rigolidarosa.com/pt-br/" target="_blank"> Wagner Rigoli da Rosa</a></p>
            </div>
        </div>
    </div>
</footer>
</section>
<script src="../public/assets/js/custom.js"></script>
<script>
    $(document).ready( function () {
        $('#table').DataTable();
    });
</script>
</body>
</html>