<!DOCTYPE html>
<html lang="en-US" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Wagner Rigoli da Rosa | Dashboard</title>
    <link rel="shortcut icon" type="image/x-icon" href="../public/assets/img/favicons/favicon.png">
    <link rel="stylesheet" crossorigin="anonymous" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==">
    <link href="https://fonts.googleapis.com/css2?family=Sora:wght@100;200;300;400;500;600;700;800&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400&amp;display=swap" rel="stylesheet">
    <link href="../public/assets/css/theme.css" rel="stylesheet" />
    <link href="../public/vendors/swiper/swiper-bundle.min.css" rel="stylesheet">
    <link href="../public/assets/css/custom.css" rel="stylesheet" />
    <script src="../public/assets/js/jquery.js"></script>



    <link href="//cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css" rel="stylesheet" />
    <script src="//cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
</head>
<body>
<section class="custom-container">
    <div class="main">
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container">
                <a class="navbar-brand" href="/dashboard"> <img src="../public/assets/img/logo.png" alt="Wagner Rigoli da Rosa" /></a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="/dashboard">Painel</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="/users">Usuários</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="/employees">Colaboradores</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="/all-overtimes">Banco de Horas</a>
                        </li>
                    </ul>
                    <div class="navbar-nav ms-auto">
                        <span class="btn">Olá <?=$_SESSION['name'];?>!</span>
                        <button class="btn btn-secondary" onclick="logout()">Sair</button>
                    </div>
                </div>
            </div>
        </nav>